project:
  type: website
  output-dir: docs

website:
  title: "Kyra Xue"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - experience.qmd
      - projects.qmd

format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

